name: catapult
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.12
  - fastapi
  - uvicorn
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - xgboost
  - statsmodels
  - tensorflow
  - torch
  - pydantic
  - joblib
  - requests
  - huggingface_hub
  - transformers
  - python-dotenv
  - accelerate
  - pip
  - pip:
      - vaderSentiment
      - newsdataapi