name: catapult
channels:
  - conda-forge
  - defaults
variables:
  TRANSFORMERS_NO_TF: 1
dependencies:
  - python=3.12
  - yfinance
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - tensorflow
  - fastapi
  - uvicorn
  - xgboost
  - statsmodels
  - pydantic
  - pip
  - pip:
      - newsdataapi
      - vaderSentiment
      - transformers
      - torch
      - python-dotenv
      - accelerate
      - boto3
      - joblib 
